name: build-compose-jb-plugins

on: workflow_dispatch

jobs:
  build:
    name: Build Compose MPP Plugins
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-java@main
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Clone repository
      run: git clone https://github.com/JetBrains/compose-jb.git --depth 1
    - name: Apply patches
      run: |
        sed -i 's/, Charsets.UTF_8/, "UTF-8"/g' ./compose-jb/gradle-plugins/preview-rpc/src/main/kotlin/org/jetbrains/compose/desktop/ui/tooling/preview/rpc/commands.kt
        sed -i 's/Charsets.UTF_8/"UTF-8"/g' ./compose-jb/gradle-plugins/preview-rpc/src/main/kotlin/org/jetbrains/compose/desktop/ui/tooling/preview/rpc/utils.kt
    - name: Build artifact (Gradle Plugin)
      run: cd ./compose-jb/gradle-plugins && ./gradlew :compose:publishToMavenLocal
    - name: Clean Useless Files
      run: find ~/.m2/repository -name 'maven-metadata-local.xml' -type f -delete
    - name: Upload Artifact (Gradle Plugin)
      uses: actions/upload-artifact@main
      with:
        name: repository
        path: ~/.m2/repository/*
    - name: Build artifact (IDEA Plugin)
      run: cd ./compose-jb/idea-plugin && ./gradlew build
    - name: Upload Artifact (IDEA Plugin)
      uses: actions/upload-artifact@main
      with:
        name: idea-plugin
        path: compose-jb/idea-plugin/build/idea-sandbox/plugins/*
