name: build-compiler

on: workflow_dispatch

jobs:
  build:
    name: Build Compose Compiler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-java@main
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Clone repository
      run: git clone https://github.com/androidx/androidx.git --depth 1
    - name: Change kotlin build target and apply patches
      run: |
        find ./androidx/buildSrc -type f -exec sed -i -e 's/jvmTarget = \"11\"/jvmTarget = \"1.8\"/g' {} \;
        sed -i 's/Integer.parseUnsignedInt(value, start, current, 10)/Integer.parseUnsignedInt(value.substring(start, current), 10)/g' ./androidx/compose/compiler/compiler-hosted/src/main/java/androidx/compose/compiler/plugins/kotlin/inference/Scheme.kt
    - name: Build artifact
      run: cd ./androidx/compose/compiler && ./gradlew compose:compiler:compiler:publishToMavenLocal compose:compiler:compiler-hosted:publishToMavenLocal
    - name: Clean Useless Files
      run: find ~/.m2/repository -name 'maven-metadata-local.xml' -type f -delete
    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: repository
        path: ~/.m2/repository/*
